/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect, useMemo } from 'react';
import { AuthProvider, useAuth } from './context/AuthContext';
import { Navbar } from './components/Navbar';
import { Sidebar } from './components/Sidebar';
import { MobileNav } from './components/MobileNav';
import { DashboardView } from './views/DashboardView';
import { AccountsView } from './views/AccountsView';
import { CalendarView } from './views/CalendarView';
import { PaymentsView } from './views/PaymentsView';
import { AnalyticsView } from './views/AnalyticsView';
import { GoalsView } from './views/GoalsView';
import { BudgetIncomeView } from './views/BudgetIncomeView';
import { SettingsView } from './views/SettingsView';
import { AuthView } from './views/AuthView';
import { AddEditAccountModal } from './components/Modals/AddEditAccountModal';
import { RecordPaymentModal } from './components/Modals/RecordPaymentModal';
import { ConfirmDeleteModal } from './components/Modals/ConfirmDeleteModal';
import { AddGoalModal } from './components/Modals/AddGoalModal';
import { ContributeGoalModal } from './components/Modals/ContributeGoalModal';
import { AddIncomeModal } from './components/Modals/AddIncomeModal';
import { AddEditBillModal } from './components/Modals/AddEditBillModal';
import { NotificationsDrawer } from './components/Modals/NotificationsDrawer';
import { OnboardingModal } from './components/Modals/OnboardingModal';
import { OfflineIndicator } from './components/OfflineIndicator';
import { checkAndTriggerDueNotifications } from './services/notificationService';
import { applyTheme, getSavedTheme } from './utils/theme';
import {
  subscribeAccounts,
  subscribeBillInstances,
  subscribePayments,
  subscribeGoals,
  subscribeNotifications,
  subscribeIncomes,
  createAccountWithBills,
  updateAccount,
  deleteAccount,
  createBillInstance,
  updateBillInstance,
  deleteBillInstance,
  cleanupAutoGeneratedFutureBills,
  markBillAsPaid,
  toggleBillSplitCollected,
  deletePayment,
  createGoal,
  updateGoal,
  deleteGoal,
  createIncome,
  updateIncome,
  deleteIncome,
  markNotificationAsRead,
  markAllNotificationsRead,
  seedArgentinaStarterAccounts,
} from './services/firestoreService';
import {
  Account,
  BillInstance,
  Payment,
  SavingsGoal,
  AppNotification,
  Income,
  CurrencyCode,
} from './types';
import { getDaysUntil } from './utils/recurrence';
import { formatDateAr } from './utils/formatters';

const MainApp: React.FC = () => {
  const { user, userProfile, loading: authLoading, completeOnboarding, bypassLoading } = useAuth();

  const [activeTab, setActiveTab] = useState<string>('dashboard');

  // Firestore real-time collections
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [bills, setBills] = useState<BillInstance[]>([]);
  const [payments, setPayments] = useState<Payment[]>([]);
  const [goals, setGoals] = useState<SavingsGoal[]>([]);
  const [incomes, setIncomes] = useState<Income[]>([]);
  const [notifications, setNotifications] = useState<AppNotification[]>([]);

  // Modals state
  const [addEditModalOpen, setAddEditModalOpen] = useState(false);
  const [accountToEdit, setAccountToEdit] = useState<Account | null>(null);

  const [recordPaymentModalOpen, setRecordPaymentModalOpen] = useState(false);
  const [selectedBillForPayment, setSelectedBillForPayment] = useState<BillInstance | null>(null);

  const [addEditBillModalOpen, setAddEditBillModalOpen] = useState(false);
  const [billToEdit, setBillToEdit] = useState<BillInstance | null>(null);
  const [preselectedAccountIdForBill, setPreselectedAccountIdForBill] = useState<string | undefined>(undefined);
  const [recentlyPaidBillId, setRecentlyPaidBillId] = useState<string | null>(null);

  const [confirmDeleteModalOpen, setConfirmDeleteModalOpen] = useState(false);
  const [deleteTarget, setDeleteTarget] = useState<{
    type: 'account' | 'payment' | 'goal' | 'income' | 'bill';
    id: string;
    name: string;
  } | null>(null);
  const [deleteLoading, setDeleteLoading] = useState(false);

  const [addGoalModalOpen, setAddGoalModalOpen] = useState(false);
  const [contributeGoalModalOpen, setContributeGoalModalOpen] = useState(false);
  const [selectedGoalForContribution, setSelectedGoalForContribution] = useState<SavingsGoal | null>(null);

  const [addIncomeModalOpen, setAddIncomeModalOpen] = useState(false);
  const [incomeToEdit, setIncomeToEdit] = useState<Income | null>(null);

  const [notificationsDrawerOpen, setNotificationsDrawerOpen] = useState(false);
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 3500);
  };

  // Dark mode class toggle
  useEffect(() => {
    const activeTheme = userProfile?.theme || getSavedTheme();
    applyTheme(activeTheme);

    if (typeof window !== 'undefined' && window.matchMedia) {
      const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)');
      const handleSystemChange = () => {
        const theme = userProfile?.theme || getSavedTheme();
        if (theme === 'system') {
          applyTheme('system');
        }
      };
      mediaQuery.addEventListener('change', handleSystemChange);
      return () => mediaQuery.removeEventListener('change', handleSystemChange);
    }
  }, [userProfile?.theme]);

  // Real-time subscriptions
  useEffect(() => {
    if (!user) {
      setAccounts([]);
      setBills([]);
      setPayments([]);
      setGoals([]);
      setIncomes([]);
      setNotifications([]);
      return;
    }

    const unsubAccounts = subscribeAccounts(user.uid, setAccounts);
    const unsubBills = subscribeBillInstances(user.uid, setBills);
    const unsubPayments = subscribePayments(user.uid, setPayments);
    const unsubGoals = subscribeGoals(user.uid, setGoals);
    const unsubIncomes = subscribeIncomes(user.uid, setIncomes);
    const unsubNotifications = subscribeNotifications(user.uid, setNotifications);

    return () => {
      unsubAccounts();
      unsubBills();
      unsubPayments();
      unsubGoals();
      unsubIncomes();
      unsubNotifications();
    };
  }, [user]);

  const defaultCurrency: CurrencyCode = userProfile?.defaultCurrency || 'ARS';

  // Proactive Due Date Reminders and Background Sync
  useEffect(() => {
    if (!user || bills.length === 0) return;

    checkAndTriggerDueNotifications(
      user.uid,
      bills,
      userProfile?.notificationSettings
    ).then((res) => {
      if (res.triggeredCount > 0) {
        console.log(`[Cuenta Clara] Disparados ${res.triggeredCount} avisos proactivos de vencimiento.`);
      }
    }).catch((err) => {
      console.warn('Error en chequeo de notificaciones de vencimiento:', err);
    });
  }, [user, bills, userProfile?.notificationSettings]);

  // Clean up any old pre-generated future speculative bills (status === 'upcoming')
  useEffect(() => {
    if (!user) return;
    cleanupAutoGeneratedFutureBills(user.uid).then((count) => {
      if (count > 0) {
        console.log(`[Cuenta Clara] Limpiados ${count} vencimientos futuros automáticos no cargados.`);
      }
    });
  }, [user]);

  // Count unread notifications
  const unreadCount = useMemo(() => {
    return notifications.filter((n) => !n.read).length;
  }, [notifications]);

  // Handlers for Accounts
  const handleSaveAccount = async (
    accountData: Omit<Account, 'id' | 'userId' | 'createdAt' | 'updatedAt'>,
    updateFutureBills = true
  ) => {
    if (!user) return;
    if (accountToEdit) {
      await updateAccount(user.uid, accountToEdit.id, accountData, updateFutureBills);
      showToast(`Cuenta "${accountData.name}" actualizada con éxito.`);
    } else {
      await createAccountWithBills(user.uid, accountData);
      showToast(`Cuenta "${accountData.name}" creada con su vencimiento.`);
    }
    setAccountToEdit(null);
  };

  const handleDuplicateAccount = async (acc: Account) => {
    if (!user) return;
    const duplicatedData = {
      name: `${acc.name} (Copia)`,
      provider: acc.provider || '',
      description: acc.description || '',
      category: acc.category,
      color: acc.color,
      icon: acc.icon,
      providerUrl: acc.providerUrl,
      clientNumber: acc.clientNumber,
      amount: acc.amount,
      currency: acc.currency,
      amountType: acc.amountType,
      frequency: acc.frequency,
      dueDay: acc.dueDay,
      nextDueDate: acc.nextDueDate,
      startDate: acc.startDate,
      paymentMethod: acc.paymentMethod,
      autopay: acc.autopay,
      status: 'active' as const,
      noticeDays: acc.noticeDays,
      notes: acc.notes,
    };
    await createAccountWithBills(user.uid, duplicatedData);
    showToast(`Se duplicó la cuenta "${acc.name}".`);
  };

  const handleTogglePause = async (acc: Account) => {
    if (!user) return;
    const newStatus = acc.status === 'paused' ? 'active' : 'paused';
    await updateAccount(user.uid, acc.id, { status: newStatus });
    showToast(newStatus === 'paused' ? `Cuenta "${acc.name}" pausada.` : `Cuenta "${acc.name}" reactivada.`);
  };

  const handleCancelAccount = async (acc: Account) => {
    if (!user) return;
    await updateAccount(user.uid, acc.id, { status: 'cancelled' });
    showToast(`Cuenta "${acc.name}" cancelada (el historial de pagos se conserva).`);
  };

  const handleArchiveAccount = async (acc: Account) => {
    if (!user) return;
    await updateAccount(user.uid, acc.id, { status: 'archived' });
    showToast(`Cuenta "${acc.name}" archivada.`);
  };

  const confirmDeleteTarget = async () => {
    if (!user || !deleteTarget) return;
    setDeleteLoading(true);
    try {
      if (deleteTarget.type === 'account') {
        await deleteAccount(user.uid, deleteTarget.id, true);
        showToast(`Cuenta "${deleteTarget.name}" eliminada.`);
      } else if (deleteTarget.type === 'bill') {
        await deleteBillInstance(user.uid, deleteTarget.id);
        showToast(`Vencimiento eliminado.`);
      } else if (deleteTarget.type === 'payment') {
        await deletePayment(user.uid, deleteTarget.id);
        showToast('Pago eliminado del historial.');
      } else if (deleteTarget.type === 'goal') {
        await deleteGoal(user.uid, deleteTarget.id);
        showToast(`Objetivo "${deleteTarget.name}" eliminado.`);
      } else if (deleteTarget.type === 'income') {
        await deleteIncome(user.uid, deleteTarget.id);
        showToast(`Ingreso "${deleteTarget.name}" eliminado.`);
      }
      setConfirmDeleteModalOpen(false);
      setDeleteTarget(null);
    } finally {
      setDeleteLoading(false);
    }
  };

  // Bill handlers (Adding / Editing / Deleting individual invoices)
  const handleOpenAddBill = (accountId?: string) => {
    setBillToEdit(null);
    setPreselectedAccountIdForBill(accountId);
    setAddEditBillModalOpen(true);
  };

  const handleEditBill = (bill: BillInstance) => {
    setBillToEdit(bill);
    setPreselectedAccountIdForBill(bill.accountId);
    setAddEditBillModalOpen(true);
  };

  const handleDeleteBill = (bill: BillInstance) => {
    setDeleteTarget({
      type: 'bill',
      id: bill.id,
      name: `${bill.accountName} (${bill.dueDate})`,
    });
    setConfirmDeleteModalOpen(true);
  };

  const handleSaveBill = async (billData: {
    accountId: string;
    accountName: string;
    category?: string;
    dueDate: string;
    amount: number;
    currency: CurrencyCode;
    notes?: string;
    isShared?: boolean;
    splitTotalPeople?: number;
    mySharePercentage?: number;
  }) => {
    if (!user) return;
    if (billToEdit) {
      await updateBillInstance(user.uid, billToEdit.id, {
        estimatedAmount: billData.amount,
        dueDate: billData.dueDate,
        currency: billData.currency,
        notes: billData.notes,
        isShared: billData.isShared,
        splitTotalPeople: billData.splitTotalPeople,
        mySharePercentage: billData.mySharePercentage,
        myShareAmount: billData.isShared ? (billData.amount * (billData.mySharePercentage || 50)) / 100 : billData.amount,
      });
      showToast(`Vencimiento de "${billData.accountName}" actualizado.`);
    } else {
      await createBillInstance(user.uid, billData);
      showToast(`Vencimiento de "${billData.accountName}" agregado con éxito.`);
    }
  };

  // Postpone bill handler (Cash flow crunch)
  const handlePostponeBill = async (
    bill: BillInstance,
    newDueDate: string,
    updateAccountToo = false,
    reason?: string
  ) => {
    if (!user) return;
    await updateBillInstance(user.uid, bill.id, {
      dueDate: newDueDate,
      postponedFrom: bill.postponedFrom || bill.dueDate,
      postponeReason: reason || 'Postergado para sincronizar con fecha de cobro',
    });

    if (updateAccountToo && bill.accountId) {
      await updateAccount(user.uid, bill.accountId, {
        nextDueDate: newDueDate,
      });
    }

    showToast(`Vencimiento de "${bill.accountName}" postergado al ${formatDateAr(newDueDate)}.`);
  };

  // Income handlers
  const handleSaveIncome = async (
    incomeData: Omit<Income, 'id' | 'userId' | 'createdAt' | 'updatedAt'>
  ) => {
    if (!user) return;
    if (incomeToEdit) {
      await updateIncome(user.uid, incomeToEdit.id, incomeData);
      showToast(`Ingreso "${incomeData.source}" actualizado.`);
    } else {
      await createIncome(user.uid, incomeData);
      showToast(`Ingreso "${incomeData.source}" registrado con éxito.`);
    }
    setIncomeToEdit(null);
  };

  // Split bill collection toggle
  const handleToggleBillSplitCollected = async (bill: BillInstance) => {
    if (!user) return;
    await toggleBillSplitCollected(user.uid, bill.id, !!bill.splitCollected);
    showToast(
      bill.splitCollected
        ? `Cobro de "${bill.accountName}" desmarcado.`
        : `¡Parte de terceros para "${bill.accountName}" marcada como cobrada!`
    );
  };

  // Payment confirmation
  const handleConfirmPayment = async (
    bill: BillInstance,
    details: {
      actualAmount: number;
      paymentDate: string;
      paymentMethod: string;
      receiptNumber?: string;
      notes?: string;
    }
  ) => {
    if (!user) return;
    setRecentlyPaidBillId(bill.id);
    await markBillAsPaid(user.uid, bill, details);
    showToast(`¡Pago de "${bill.accountName}" registrado con éxito!`);
  };

  // Seed Argentina Accounts
  const handleSeedStarterData = async () => {
    if (!user) return;
    await seedArgentinaStarterAccounts(user.uid, defaultCurrency);
    showToast('¡Se cargaron 5 servicios esenciales de Argentina con sus vencimientos!');
  };

  // Complete Onboarding
  const handleFinishOnboarding = async (
    currency: CurrencyCode,
    timezone: string,
    importStarterData: boolean
  ) => {
    if (!user) return;
    await completeOnboarding(currency, timezone);
    if (importStarterData) {
      await seedArgentinaStarterAccounts(user.uid, currency);
    }
    showToast('¡Cuenta configurada con éxito!');
  };

  // Goals
  const handleSaveGoal = async (goalData: Omit<SavingsGoal, 'id' | 'userId' | 'createdAt' | 'updatedAt'>) => {
    if (!user) return;
    await createGoal(user.uid, goalData);
    showToast(`Objetivo "${goalData.name}" creado.`);
  };

  const handleContributeGoal = async (goalId: string, addedAmount: number) => {
    if (!user) return;
    const goal = goals.find((g) => g.id === goalId);
    if (!goal) return;
    const newAmt = goal.currentAmount + addedAmount;
    const newStatus = newAmt >= goal.targetAmount ? 'achieved' : goal.status;
    await updateGoal(user.uid, goalId, {
      currentAmount: newAmt,
      status: newStatus,
    });
    showToast(`¡Se sumó ${defaultCurrency} ${addedAmount} al objetivo "${goal.name}"!`);
  };

  // Loading Screen
  if (authLoading) {
    return (
      <div className="min-h-[100dvh] bg-slate-900 flex flex-col items-center justify-center p-6 text-center select-none">
        <div className="w-12 h-12 border-4 border-teal-500 border-t-transparent rounded-full animate-spin mb-4 shadow-lg shadow-teal-500/20" />
        <p className="text-white font-bold text-base tracking-tight">Cargando Cuenta Clara...</p>
        <p className="text-xs text-slate-400 mt-1 max-w-xs mx-auto">
          Optimizando datos para tu dispositivo
        </p>

        {/* Mobile slow network bypass button */}
        <div className="mt-8 pt-4 border-t border-slate-800/80 max-w-xs mx-auto">
          <p className="text-[11px] text-slate-400 mb-2">
            ¿La señal de tu celular es lenta o tarda en conectar?
          </p>
          <button
            onClick={bypassLoading}
            className="px-4 py-2 bg-teal-600 hover:bg-teal-500 active:scale-95 text-white rounded-xl text-xs font-semibold shadow-md transition-all"
          >
            Continuar a la app de inmediato
          </button>
        </div>
      </div>
    );
  }

  // Not logged in -> Auth Screen
  if (!user) {
    return <AuthView />;
  }

  return (
    <div className="min-h-[100dvh] bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-slate-100 flex flex-col">
      {/* Navbar */}
      <Navbar
        onOpenAddAccount={() => {
          setAccountToEdit(null);
          setAddEditModalOpen(true);
        }}
        onOpenNotifications={() => setNotificationsDrawerOpen(true)}
        unreadCount={unreadCount}
        activeTab={activeTab}
        setActiveTab={setActiveTab}
      />

      {/* Main Body */}
      <div className="flex-1 flex max-w-7xl w-full mx-auto pb-24 sm:pb-28 lg:pb-8">
        {/* Desktop Sidebar */}
        <Sidebar
          activeTab={activeTab}
          setActiveTab={setActiveTab}
          activeAccountsCount={accounts.filter((a) => a.status === 'active').length}
        />

        {/* Content Area */}
        <main className="flex-1 w-full p-3 sm:p-6 lg:p-8 min-w-0">
          {activeTab === 'dashboard' && (
            <DashboardView
              accounts={accounts}
              bills={bills}
              payments={payments}
              incomes={incomes}
              goals={goals}
              onOpenAddIncome={() => {
                setIncomeToEdit(null);
                setAddIncomeModalOpen(true);
              }}
              onOpenAddGoal={() => {
                setAddGoalModalOpen(true);
              }}
              onNavigateToTab={(tab) => setActiveTab(tab)}
              onOpenAddAccount={() => {
                setAccountToEdit(null);
                setAddEditModalOpen(true);
              }}
              onOpenRecordPayment={(bill) => {
                setSelectedBillForPayment(bill);
                setRecordPaymentModalOpen(true);
              }}
              onEditAccount={(acc) => {
                setAccountToEdit(acc);
                setAddEditModalOpen(true);
              }}
              onDeleteAccount={(acc) => {
                setDeleteTarget({
                  type: 'account',
                  id: acc.id,
                  name: acc.name,
                });
                setConfirmDeleteModalOpen(true);
              }}
              onOpenAddBill={handleOpenAddBill}
              onEditBill={handleEditBill}
              onDeleteBill={handleDeleteBill}
              onPostponeBill={handlePostponeBill}
              recentlyPaidBillId={recentlyPaidBillId}
              onSeedStarterData={handleSeedStarterData}
              defaultCurrency={defaultCurrency}
              userName={userProfile?.displayName || user.displayName || 'Usuario'}
            />
          )}

          {activeTab === 'accounts' && (
            <AccountsView
              accounts={accounts}
              onOpenAddAccount={() => {
                setAccountToEdit(null);
                setAddEditModalOpen(true);
              }}
              onEditAccount={(acc) => {
                setAccountToEdit(acc);
                setAddEditModalOpen(true);
              }}
              onDuplicateAccount={handleDuplicateAccount}
              onTogglePauseAccount={handleTogglePause}
              onCancelAccount={handleCancelAccount}
              onArchiveAccount={handleArchiveAccount}
              onDeleteAccount={(acc) => {
                setDeleteTarget({
                  type: 'account',
                  id: acc.id,
                  name: acc.name,
                });
                setConfirmDeleteModalOpen(true);
              }}
              onOpenAddBill={handleOpenAddBill}
            />
          )}

          {activeTab === 'budget' && (
            <BudgetIncomeView
              incomes={incomes}
              accounts={accounts}
              bills={bills}
              goals={goals}
              onOpenAddIncome={() => {
                setIncomeToEdit(null);
                setAddIncomeModalOpen(true);
              }}
              onEditIncome={(inc) => {
                setIncomeToEdit(inc);
                setAddIncomeModalOpen(true);
              }}
              onDeleteIncome={async (incId) => {
                const inc = incomes.find((item) => item.id === incId);
                setDeleteTarget({
                  type: 'income',
                  id: incId,
                  name: inc?.source || 'ingreso',
                });
                setConfirmDeleteModalOpen(true);
              }}
              onEditAccount={(acc) => {
                setAccountToEdit(acc);
                setAddEditModalOpen(true);
              }}
              onDeleteAccount={(acc) => {
                setDeleteTarget({
                  type: 'account',
                  id: acc.id,
                  name: acc.name,
                });
                setConfirmDeleteModalOpen(true);
              }}
              onToggleBillSplitCollected={handleToggleBillSplitCollected}
              defaultCurrency={defaultCurrency}
            />
          )}

          {activeTab === 'calendar' && (
            <CalendarView
              bills={bills}
              onOpenRecordPayment={(bill) => {
                setSelectedBillForPayment(bill);
                setRecordPaymentModalOpen(true);
              }}
              onOpenAddBill={() => handleOpenAddBill()}
              defaultCurrency={defaultCurrency}
            />
          )}

          {activeTab === 'payments' && (
            <PaymentsView
              payments={payments}
              onDeletePayment={async (pId) => {
                setDeleteTarget({
                  type: 'payment',
                  id: pId,
                  name: 'comprobante de pago',
                });
                setConfirmDeleteModalOpen(true);
              }}
              defaultCurrency={defaultCurrency}
            />
          )}

          {activeTab === 'analytics' && (
            <AnalyticsView
              accounts={accounts}
              bills={bills}
              payments={payments}
              incomes={incomes}
              goals={goals}
              defaultCurrency={defaultCurrency}
              userName={userProfile?.displayName || user.displayName || 'Usuario'}
            />
          )}

          {activeTab === 'goals' && (
            <GoalsView
              goals={goals}
              onOpenAddGoal={() => setAddGoalModalOpen(true)}
              onOpenContributeGoal={(goal) => {
                setSelectedGoalForContribution(goal);
                setContributeGoalModalOpen(true);
              }}
              onDeleteGoal={async (gId) => {
                const g = goals.find((item) => item.id === gId);
                setDeleteTarget({
                  type: 'goal',
                  id: gId,
                  name: g?.name || 'objetivo de ahorro',
                });
                setConfirmDeleteModalOpen(true);
              }}
              defaultCurrency={defaultCurrency}
            />
          )}

          {activeTab === 'settings' && <SettingsView />}
        </main>
      </div>

      {/* Mobile Bottom Navigation */}
      <MobileNav activeTab={activeTab} setActiveTab={setActiveTab} />

      {/* MODALS */}
      {/* Add / Edit Account */}
      <AddEditAccountModal
        isOpen={addEditModalOpen}
        onClose={() => {
          setAddEditModalOpen(false);
          setAccountToEdit(null);
        }}
        onSave={handleSaveAccount}
        accountToEdit={accountToEdit}
        defaultCurrency={defaultCurrency}
        onDeleteAccount={(acc) => {
          setDeleteTarget({
            type: 'account',
            id: acc.id,
            name: acc.name,
          });
          setConfirmDeleteModalOpen(true);
        }}
      />

      {/* Record Payment */}
      <RecordPaymentModal
        isOpen={recordPaymentModalOpen}
        onClose={() => {
          setRecordPaymentModalOpen(false);
          setSelectedBillForPayment(null);
        }}
        bill={selectedBillForPayment}
        onConfirmPayment={handleConfirmPayment}
      />

      {/* Add Goal */}
      <AddGoalModal
        isOpen={addGoalModalOpen}
        onClose={() => setAddGoalModalOpen(false)}
        onSave={handleSaveGoal}
        accounts={accounts}
        defaultCurrency={defaultCurrency}
      />

      {/* Contribute to Goal */}
      <ContributeGoalModal
        isOpen={contributeGoalModalOpen}
        onClose={() => {
          setContributeGoalModalOpen(false);
          setSelectedGoalForContribution(null);
        }}
        goal={selectedGoalForContribution}
        onContribute={handleContributeGoal}
      />

      {/* Add / Edit Income */}
      <AddIncomeModal
        isOpen={addIncomeModalOpen}
        onClose={() => {
          setAddIncomeModalOpen(false);
          setIncomeToEdit(null);
        }}
        onSave={handleSaveIncome}
        incomeToEdit={incomeToEdit}
        defaultCurrency={defaultCurrency}
      />

      {/* Confirm Delete */}
      <ConfirmDeleteModal
        isOpen={confirmDeleteModalOpen}
        onClose={() => {
          setConfirmDeleteModalOpen(false);
          setDeleteTarget(null);
        }}
        onConfirm={confirmDeleteTarget}
        title={`¿Eliminar ${
          deleteTarget?.type === 'account'
            ? 'cuenta'
            : deleteTarget?.type === 'goal'
            ? 'objetivo'
            : deleteTarget?.type === 'income'
            ? 'ingreso'
            : deleteTarget?.type === 'bill'
            ? 'vencimiento'
            : 'pago'
        }?`}
        message={`Esta acción eliminará permanentemente "${deleteTarget?.name}". No se podrá deshacer.`}
        loading={deleteLoading}
      />

      {/* Add / Edit Bill Modal */}
      <AddEditBillModal
        isOpen={addEditBillModalOpen}
        onClose={() => {
          setAddEditBillModalOpen(false);
          setBillToEdit(null);
          setPreselectedAccountIdForBill(undefined);
        }}
        accounts={accounts}
        billToEdit={billToEdit}
        preselectedAccountId={preselectedAccountIdForBill}
        defaultCurrency={defaultCurrency}
        onSave={handleSaveBill}
        onOpenAddAccount={() => {
          setAddEditBillModalOpen(false);
          setAccountToEdit(null);
          setAddEditModalOpen(true);
        }}
      />

      {/* Notifications Drawer */}
      <NotificationsDrawer
        isOpen={notificationsDrawerOpen}
        onClose={() => setNotificationsDrawerOpen(false)}
        notifications={notifications}
        onOpenSettings={() => setActiveTab('settings')}
        onMarkAsRead={async (id) => {
          if (!user) return;
          await markNotificationAsRead(user.uid, id);
        }}
        onMarkAllAsRead={async () => {
          if (!user) return;
          await markAllNotificationsRead(user.uid, notifications);
        }}
      />

      {/* Offline Connectivity Indicator */}
      <OfflineIndicator />

      {/* Onboarding for first time user */}
      <OnboardingModal
        isOpen={!!userProfile && !userProfile.onboarded}
        onFinish={handleFinishOnboarding}
      />

      {/* Toast Notification */}
      {toastMessage && (
        <div className="fixed bottom-16 sm:bottom-6 right-4 sm:right-6 z-50 bg-slate-900 text-white px-4 py-3 rounded-xl shadow-xl border border-slate-700 text-xs font-semibold flex items-center gap-2 animate-in fade-in slide-in-from-bottom-2 duration-200">
          <span className="w-2 h-2 rounded-full bg-teal-400" />
          <span>{toastMessage}</span>
        </div>
      )}
    </div>
  );
};

export default function App() {
  return (
    <AuthProvider>
      <MainApp />
    </AuthProvider>
  );
}
